/**
 * Block System
 *
 * Exports for the block-based content system.
 *
 * @see docs/projects/PAGE_PRESENTATION_SYSTEM.md
 */

// Core types (excluding createBlock which is re-exported from registry with a better implementation)
export {
  blockCategorySchema,
  type BlockCategory,
  blockTypeSchema,
  type BlockType,
  blockIdSchema,
  type BlockId,
  baseBlockSchema,
  type BaseBlock,
  type BlockDefinition,
  type BlockRenderContext,
  type BlockRendererProps,
  blockListSchema,
  type BlockList,
  type BlockData,
  type BlockDataMap,
  BLOCK_TYPES_BY_CATEGORY,
  CONTAINER_BLOCK_TYPES,
  EMAIL_EXCLUDED_BLOCK_TYPES,
  EMAIL_COMPATIBLE_BLOCK_TYPES,
} from "./types";

// Registry (includes createBlock and other registry functions)
export {
  allBlockDefinitions,
  blockRegistry,
  getBlockDefinition,
  requireBlockDefinition,
  getBlockDefinitionsByCategory,
  getEmailCompatibleBlockDefinitions,
  getContainerBlockDefinitions,
  isEmailCompatible,
  isContainerBlock,
  searchBlockDefinitions,
  createDefaultBlock,
  createBlock,
  validateBlock,
  validateBlocks,
  filterBlocksForEmail,
  getAllowedChildTypes,
  isChildTypeAllowed,
  textBlockDefinitions,
  mediaBlockDefinitions,
  layoutBlockDefinitions,
  interactiveBlockDefinitions,
  embedBlockDefinitions,
  navigationBlockDefinitions,
  dataBlockDefinitions,
} from "./registry";

// Text blocks
export {
  textBlockDataSchema,
  textBlockSchema,
  textBlockDefinition,
  headingBlockDataSchema,
  headingBlockSchema,
  headingBlockDefinition,
  paragraphBlockDataSchema,
  paragraphBlockSchema,
  paragraphBlockDefinition,
  listBlockDataSchema,
  listBlockSchema,
  listBlockDefinition,
  listItemSchema,
  quoteBlockDataSchema,
  quoteBlockSchema,
  quoteBlockDefinition,
  codeBlockDataSchema,
  codeBlockSchema,
  codeBlockDefinition,
  type TextBlockData,
  type TextBlock,
  type HeadingBlockData,
  type HeadingBlock,
  type ParagraphBlockData,
  type ParagraphBlock,
  type ListBlockData,
  type ListBlock,
  type ListItem,
  type QuoteBlockData,
  type QuoteBlock,
  type CodeBlockData,
  type CodeBlock,
} from "./schemas/text";

// Media blocks
export {
  imageBlockDataSchema,
  imageBlockSchema,
  imageBlockDefinition,
  galleryBlockDataSchema,
  galleryBlockSchema,
  galleryBlockDefinition,
  galleryImageSchema,
  videoBlockDataSchema,
  videoBlockSchema,
  videoBlockDefinition,
  audioBlockDataSchema,
  audioBlockSchema,
  audioBlockDefinition,
  fileBlockDataSchema,
  fileBlockSchema,
  fileBlockDefinition,
  type ImageBlockData,
  type ImageBlock,
  type GalleryBlockData,
  type GalleryBlock,
  type GalleryImage,
  type VideoBlockData,
  type VideoBlock,
  type AudioBlockData,
  type AudioBlock,
  type FileBlockData,
  type FileBlock,
} from "./schemas/media";

// Layout blocks
export {
  columnsBlockDataSchema,
  columnsBlockSchema,
  columnsBlockDefinition,
  columnSchema,
  dividerBlockDataSchema,
  dividerBlockSchema,
  dividerBlockDefinition,
  spacerBlockDataSchema,
  spacerBlockSchema,
  spacerBlockDefinition,
  cardBlockDataSchema,
  cardBlockSchema,
  cardBlockDefinition,
  accordionBlockDataSchema,
  accordionBlockSchema,
  accordionBlockDefinition,
  accordionItemSchema,
  tabsBlockDataSchema,
  tabsBlockSchema,
  tabsBlockDefinition,
  tabItemSchema,
  carouselBlockDataSchema,
  carouselBlockSchema,
  carouselBlockDefinition,
  carouselSlideSchema,
  type ColumnsBlockData,
  type ColumnsBlock,
  type Column,
  type DividerBlockData,
  type DividerBlock,
  type SpacerBlockData,
  type SpacerBlock,
  type CardBlockData,
  type CardBlock,
  type AccordionBlockData,
  type AccordionBlock,
  type AccordionItem,
  type TabsBlockData,
  type TabsBlock,
  type TabItem,
  type CarouselBlockData,
  type CarouselBlock,
  type CarouselSlide,
} from "./schemas/layout";

// Interactive blocks
export {
  buttonBlockDataSchema,
  buttonBlockSchema,
  buttonBlockDefinition,
  buttonGroupBlockDataSchema,
  buttonGroupBlockSchema,
  buttonGroupBlockDefinition,
  buttonGroupItemSchema,
  formBlockDataSchema,
  formBlockSchema,
  formBlockDefinition,
  formFieldSchema,
  interactiveCalendarBlockDataSchema,
  interactiveCalendarBlockSchema,
  interactiveCalendarBlockDefinition,
  mapBlockDataSchema,
  mapBlockSchema,
  mapBlockDefinition,
  mapMarkerSchema,
  searchBlockDataSchema,
  searchBlockSchema,
  searchBlockDefinition,
  type ButtonBlockData,
  type ButtonBlock,
  type ButtonGroupBlockData,
  type ButtonGroupBlock,
  type ButtonGroupItem,
  type FormBlockData,
  type FormBlock,
  type FormField,
  type InteractiveCalendarBlockData,
  type InteractiveCalendarBlock,
  type MapBlockData,
  type MapBlock,
  type MapMarker,
  type SearchBlockData,
  type SearchBlock,
} from "./schemas/interactive";

// Embed blocks
export {
  htmlBlockDataSchema,
  htmlBlockSchema,
  htmlBlockDefinition,
  iframeBlockDataSchema,
  iframeBlockSchema,
  iframeBlockDefinition,
  socialEmbedBlockDataSchema,
  socialEmbedBlockSchema,
  socialEmbedBlockDefinition,
  type HtmlBlockData,
  type HtmlBlock,
  type IframeBlockData,
  type IframeBlock,
  type SocialEmbedBlockData,
  type SocialEmbedBlock,
} from "./schemas/embed";

// Navigation blocks
export {
  menuBlockDataSchema,
  menuBlockSchema,
  menuBlockDefinition,
  menuItemSchema,
  breadcrumbBlockDataSchema,
  breadcrumbBlockSchema,
  breadcrumbBlockDefinition,
  breadcrumbItemSchema,
  tableOfContentsBlockDataSchema,
  tableOfContentsBlockSchema,
  tableOfContentsBlockDefinition,
  type MenuBlockData,
  type MenuBlock,
  type MenuItem,
  type BreadcrumbBlockData,
  type BreadcrumbBlock,
  type BreadcrumbItem,
  type TableOfContentsBlockData,
  type TableOfContentsBlock,
} from "./schemas/navigation";

// Data blocks
export {
  tableBlockDataSchema,
  tableBlockSchema,
  tableBlockDefinition,
  tableCellSchema,
  tableRowSchema,
  tableColumnSchema,
  placeholderBlockDataSchema,
  placeholderBlockSchema,
  placeholderBlockDefinition,
  type TableBlockData,
  type TableBlock,
  type TableCell,
  type TableRow,
  type TableColumn,
  type PlaceholderBlockData,
  type PlaceholderBlock,
} from "./schemas/data";
